/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Contract */
        post: operations["upload_contract_api_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rewrite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rewrite */
        post: operations["rewrite_api_rewrite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Contract Map
         * @description Accepts {"contract_text": "..."} and returns structure[] and timeline[].
         */
        post: operations["get_contract_map_api_map_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Question Endpoint
         * @description Accepts {"contract_text": "...", "question": "..."} and returns {"answer": "..."}.
         */
        post: operations["ask_question_endpoint_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Risk Scan Endpoint */
        post: operations["scan_clause_api_risk_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contextualize/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Clause */
        post: operations["explain_clause_api_contextualize_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nlp/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Structured Clause Analysis */
        post: operations["analyze_contract_api_nlp_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kg/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a Document into the Knowledge Graph */
        post: operations["ingest_document_api_kg_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kg/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find Clauses Using a Defined Term */
        post: operations["query_term_api_kg_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kg/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find Candidate Cross-Document Conflicts */
        post: operations["query_conflicts_api_kg_conflicts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Agentic Case Analysis */
        post: operations["analyze_case_api_agents_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Router status */
        get: operations["models_status_api_models_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a stored document */
        get: operations["get_document_api_v2_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/documents/{document_id}/sensitivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a document's sensitivity tier and why */
        get: operations["get_sensitivity_api_v2_documents__document_id__sensitivity_get"];
        /** Override a document's sensitivity tier (org-admin) */
        put: operations["override_sensitivity_api_v2_documents__document_id__sensitivity_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/documents/{document_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the planner-driven agent analysis */
        post: operations["analyze_api_v2_documents__document_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/documents/{document_id}/rewrite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plain-English rewrite of the document or one block */
        post: operations["rewrite_api_v2_documents__document_id__rewrite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/documents/{document_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Structure + timeline for the document */
        post: operations["contract_map_api_v2_documents__document_id__map_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/documents/{document_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a question grounded on the document */
        post: operations["ask_api_v2_documents__document_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/documents/{document_id}/risk-scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rule + AI risk scan of the document or one block */
        post: operations["risk_scan_api_v2_documents__document_id__risk_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/documents/{document_id}/contextualize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain one block's clause for a user's context */
        post: operations["contextualize_api_v2_documents__document_id__contextualize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentAnalyzeRequest */
        AgentAnalyzeRequest: {
            /** Document Id */
            document_id: number;
            /**
             * Analysis Mode
             * @description Planner preset: 'full' (all agents), 'quick' (skip RAG research), 'risk_only' (flags only), 'extract_only' (clauses + the verifier gate only). The planner still prunes 'full' when a document has no risk/ambiguity signal.
             * @default full
             */
            analysis_mode: string;
            /**
             * Use Ai Planner
             * @description Let an LLM choose which agents run (falls back to the rule-based planner when no self-hosted model is served).
             * @default false
             */
            use_ai_planner: boolean;
        };
        /** AgentAnalyzeResponse */
        AgentAnalyzeResponse: {
            /** Document Id */
            document_id: number;
            /** Clause Count */
            clause_count: number;
            /**
             * Sensitivity Tier
             * @description The document's sensitivity tier. confidential/privileged documents are never routed to an external provider during this analysis.
             * @default internal
             */
            sensitivity_tier: string;
            /**
             * External Providers Permitted
             * @description False when the tier + settings forbid any Class C (external) routing.
             * @default true
             */
            external_providers_permitted: boolean;
            /**
             * Plan
             * @description The ordered agent node ids the planner ran (ends with 'verifier').
             */
            plan?: string[];
            /**
             * Plan Rationale
             * @description Why the planner chose that plan.
             * @default
             */
            plan_rationale: string;
            /** Risk Findings */
            risk_findings?: components["schemas"]["RiskFinding"][];
            /** Kg Conflicts */
            kg_conflicts?: components["schemas"]["KGConflictFinding"][];
            /** Summary */
            summary: string;
            /**
             * Faithfulness Ok
             * @description Each summary claim is entailed by a retrieved source (NLI check). False means a claim was contradicted or left unsupported -- see unsupported_claims.
             */
            faithfulness_ok: boolean;
            /**
             * Faithfulness Method
             * @description 'nli' = real entailment head (Class A DeBERTa/ModernBERT); 'lexical_fallback' = the NLI head isn't installed, a weaker vocabulary-overlap check ran
             * @default nli
             */
            faithfulness_method: string;
            /**
             * Unsupported Claims
             * @description Claim sentences a source contradicted or failed to support (NLI method only)
             */
            unsupported_claims?: string[];
            /**
             * Invalid Citation Numbers
             * @description Non-empty means the summary cited a source it was never given
             */
            invalid_citation_numbers?: number[];
            /** Needs Human Review */
            needs_human_review: boolean;
            /** Trace */
            trace?: components["schemas"]["AgentStep"][];
        };
        /**
         * AgentStep
         * @description One row of the audit trail -- also what gets persisted to the
         *     `agent_traces` table (db_models.py) after a run completes.
         */
        AgentStep: {
            /** Agent Name */
            agent_name: string;
            /** Input Summary */
            input_summary: string;
            /** Output Summary */
            output_summary: string;
        };
        /** AmbiguityFlag */
        AmbiguityFlag: {
            /** Term */
            term: string;
            /** Explanation */
            explanation: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Contract Text */
            contract_text: string;
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
        };
        /** Body_upload_contract_api_upload_post */
        Body_upload_contract_api_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** ClauseObject */
        ClauseObject: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            /** Clause Type */
            clause_type: string;
            /**
             * Clause Type Source
             * @default rule
             */
            clause_type_source: string;
            /** Entities */
            entities?: components["schemas"]["EntityMention"][];
            /** Defined Terms Used */
            defined_terms_used?: string[];
            /** Cross References */
            cross_references?: components["schemas"]["CrossReference"][];
            /** Deontic Tags */
            deontic_tags?: components["schemas"]["DeonticTag"][];
            /** Temporal Expressions */
            temporal_expressions?: components["schemas"]["TemporalExpression"][];
            /** Ambiguity Flags */
            ambiguity_flags?: components["schemas"]["AmbiguityFlag"][];
            /** Pronoun Candidates */
            pronoun_candidates?: string[];
        };
        /** ContextualRiskFlag */
        ContextualRiskFlag: {
            /** Term */
            term: string;
            /** Explanation */
            explanation: string;
        };
        /** ContextualizerRequest */
        ContextualizerRequest: {
            /**
             * Text
             * @description Contract clause text to explain
             */
            text: string;
            /**
             * Context
             * @description User context including role, location, contract_type, interests, tone
             */
            context: {
                [key: string]: unknown;
            };
        };
        /** ContextualizerResponse */
        ContextualizerResponse: {
            /** Clause */
            clause: string;
            /** Context */
            context: {
                [key: string]: unknown;
            };
            /** Explanation */
            explanation: string;
            /**
             * Used Hints
             * @description Contextual hints used in the explanation
             */
            used_hints?: string[];
            /**
             * Citations
             * @description The retrieved knowledge-base entries backing used_hints, each with its source citation (or null if this is a general principle with no single controlling citation -- see services/rag/corpus.py). Additive field; used_hints is unchanged for backward compatibility.
             */
            citations?: {
                [key: string]: unknown;
            }[];
            /**
             * Citation Warning
             * @description True if the model referenced a bracket citation number it wasn't actually given.
             * @default false
             */
            citation_warning: boolean;
        };
        /** CrossReference */
        CrossReference: {
            /** Text */
            text: string;
        };
        /** DeonticTag */
        DeonticTag: {
            /** Modality */
            modality: string;
            /** Trigger Phrase */
            trigger_phrase: string;
            /** Actor */
            actor?: string | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Source
             * @default rule
             */
            source: string;
        };
        /** DocumentSection */
        DocumentSection: {
            /** Title */
            title: string;
            /** Content Summary */
            content_summary: string;
            /** Subsections */
            subsections?: components["schemas"]["DocumentSection"][];
        };
        /** EntityMention */
        EntityMention: {
            /** Text */
            text: string;
            /** Type */
            type: string;
        };
        /** FlaggedClause */
        FlaggedClause: {
            /** Clause */
            clause: string;
            /** Keyword Flags */
            keyword_flags?: components["schemas"]["KeywordRiskFlag"][];
            /** Contextual Flags */
            contextual_flags?: components["schemas"]["ContextualRiskFlag"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KGConflictFinding */
        KGConflictFinding: {
            /** Term */
            term: string;
            /** Obligation Clause */
            obligation_clause: string;
            /** Prohibition Clause */
            prohibition_clause: string;
            /** Obligation Document Id */
            obligation_document_id: number;
            /** Prohibition Document Id */
            prohibition_document_id: number;
        };
        /** KGConflictsResponse */
        KGConflictsResponse: {
            /** Term */
            term: string;
            /** Conflicts */
            conflicts?: {
                [key: string]: unknown;
            }[];
        };
        /** KGIngestRequest */
        KGIngestRequest: {
            /** Document Id */
            document_id: number;
        };
        /** KGIngestResponse */
        KGIngestResponse: {
            /** Document Id */
            document_id: number;
            /** Clauses */
            clauses: number;
            /** Defined Terms */
            defined_terms: number;
            /** Cross References */
            cross_references: number;
            /** Portfolio Links Created */
            portfolio_links_created: number;
            /**
             * Kg Available
             * @description False if Memgraph was unreachable -- the ingest call still succeeds (fail-soft), it just wrote nothing.
             */
            kg_available: boolean;
        };
        /** KGQueryRequest */
        KGQueryRequest: {
            /** Term */
            term: string;
        };
        /** KGQueryResponse */
        KGQueryResponse: {
            /** Term */
            term: string;
            /** Clauses */
            clauses?: {
                [key: string]: unknown;
            }[];
        };
        /** KeywordRiskFlag */
        KeywordRiskFlag: {
            /** Term */
            term: string;
            /** Predefined Explanation */
            predefined_explanation: string;
        };
        /** MapRequest */
        MapRequest: {
            /** Contract Text */
            contract_text: string;
        };
        /** MapResponse */
        MapResponse: {
            /** Structure */
            structure: components["schemas"]["DocumentSection"][];
            /** Timeline */
            timeline: components["schemas"]["TimelineEvent"][];
        };
        /** ModelProviderStatus */
        ModelProviderStatus: {
            /** Name */
            name: string;
            /**
             * Hosting Class
             * @description A (deterministic/CPU), B (self-hosted neural), C (external API)
             */
            hosting_class: string;
            /** Capabilities */
            capabilities?: string[];
            /**
             * Available
             * @description Provider's own is_available() -- config present, dependency importable
             */
            available: boolean;
            /**
             * Leaves Perimeter
             * @description True only for Class C providers that call a third-party API
             */
            leaves_perimeter: boolean;
            /** Models */
            models?: string[];
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ModelsStatusResponse */
        ModelsStatusResponse: {
            /** Providers */
            providers: components["schemas"]["ModelProviderStatus"][];
            /** Policy Version */
            policy_version: number;
            /** External Providers Enabled */
            external_providers_enabled: boolean;
            /** Strict Local Only */
            strict_local_only: boolean;
        };
        /** NlpAnalyzeRequest */
        NlpAnalyzeRequest: {
            /** Contract Text */
            contract_text: string;
            /**
             * Use Ai Escalation
             * @description If true, clauses the rule-based deontic tagger/classifier can't confidently handle are escalated to Gemini. Off by default for determinism/speed/cost.
             * @default false
             */
            use_ai_escalation: boolean;
        };
        /** NlpAnalyzeResponse */
        NlpAnalyzeResponse: {
            /** Clauses */
            clauses: components["schemas"]["ClauseObject"][];
        };
        /** RewriteRequest */
        RewriteRequest: {
            /** Text */
            text: string;
            /**
             * Mode
             * @default layman
             */
            mode: string;
        };
        /** RewriteResponse */
        RewriteResponse: {
            /** Rewritten Text */
            rewritten_text: string;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** RiskFinding */
        RiskFinding: {
            /** Clause Id */
            clause_id: number;
            /** Term */
            term: string;
            /** Explanation */
            explanation: string;
            /** Source */
            source: string;
        };
        /** RiskScanRequest */
        RiskScanRequest: {
            /** Text */
            text: string;
        };
        /** RiskScanResponse */
        RiskScanResponse: {
            /** Flagged Clauses */
            flagged_clauses: components["schemas"]["FlaggedClause"][];
            /** Risk Summary */
            risk_summary: string;
        };
        /** SensitivityOverrideRequest */
        SensitivityOverrideRequest: {
            /** Tier */
            tier: string;
            /**
             * Reason
             * @description Recorded in the audit log.
             */
            reason: string;
        };
        /** SensitivityResponse */
        SensitivityResponse: {
            /** Document Id */
            document_id: number;
            /** Tier */
            tier: string;
            /**
             * Source
             * @description 'auto' (rule classifier) or 'override' (org-admin set it)
             */
            source: string;
            /**
             * Signals
             * @description The phrases that drove the tier.
             */
            signals?: {
                [key: string]: unknown;
            }[];
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * External Providers Permitted
             * @description False => every model call for this document stays on self-hosted providers.
             */
            external_providers_permitted: boolean;
        };
        /** TemporalExpression */
        TemporalExpression: {
            /** Text */
            text: string;
            /** Normalized Date */
            normalized_date?: string | null;
        };
        /** TimelineEvent */
        TimelineEvent: {
            /** Date Description */
            date_description: string;
            /** Event */
            event: string;
        };
        /** V2AnalyzeRequest */
        V2AnalyzeRequest: {
            /**
             * Analysis Mode
             * @default full
             */
            analysis_mode: string;
            /**
             * Use Ai Planner
             * @default false
             */
            use_ai_planner: boolean;
        };
        /** V2AskRequest */
        V2AskRequest: {
            /** Question */
            question: string;
        };
        /** V2ContextualizeRequest */
        V2ContextualizeRequest: {
            /**
             * Block Id
             * @description The block id whose clause to explain.
             */
            block_id: number | string;
            /**
             * Context
             * @description User context: role, location, contract_type, interests, tone.
             */
            context: {
                [key: string]: unknown;
            };
        };
        /** V2DocumentResponse */
        V2DocumentResponse: {
            /** Document Id */
            document_id: number;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type?: string | null;
            /** Full Text */
            full_text: string;
            /** Blocks */
            blocks?: {
                [key: string]: unknown;
            }[];
            /** Created At */
            created_at?: string | null;
            /**
             * Sensitivity Tier
             * @default internal
             */
            sensitivity_tier: string;
            /**
             * Sensitivity Source
             * @default auto
             */
            sensitivity_source: string;
        };
        /** V2RewriteRequest */
        V2RewriteRequest: {
            /**
             * Block Id
             * @description A block id from the upload response; omit to rewrite the whole document.
             */
            block_id?: number | string | null;
            /**
             * Mode
             * @default layman
             */
            mode: string;
        };
        /** V2RiskScanRequest */
        V2RiskScanRequest: {
            /**
             * Block Id
             * @description A block id; omit to scan the whole document.
             */
            block_id?: number | string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_contract_api_upload_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_contract_api_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rewrite_api_rewrite_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_map_api_map_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_question_endpoint_api_ask_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_clause_api_risk_scan_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_clause_api_contextualize_scan_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextualizerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextualizerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_contract_api_nlp_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NlpAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NlpAnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_document_api_kg_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KGIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KGIngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_term_api_kg_query_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KGQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KGQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_conflicts_api_kg_conflicts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KGQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KGConflictsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_case_api_agents_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_status_api_models_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v2_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sensitivity_api_v2_documents__document_id__sensitivity_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensitivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_sensitivity_api_v2_documents__document_id__sensitivity_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensitivityOverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensitivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_v2_documents__document_id__analyze_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["V2AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rewrite_api_v2_documents__document_id__rewrite_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["V2RewriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contract_map_api_v2_documents__document_id__map_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_v2_documents__document_id__ask_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_scan_api_v2_documents__document_id__risk_scan_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["V2RiskScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contextualize_api_v2_documents__document_id__contextualize_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ContextualizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextualizerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
