apiVersion: v1
kind: Secret
metadata:
  name: legalai-backend-secrets
type: Opaque
stringData:
  LLM_BASE_URL: "http://legalai-ollama:11434/v1"
  EMBEDDING_BASE_URL: "http://legalai-tei-embed:80"
  RERANKER_BASE_URL: "http://legalai-tei-rerank:80"
